alias: 로또 당첨 결과 알림 입니다
description: ""
triggers:
  - entity_id:
      - sensor.dhlotto_xxxxxxxx_lotto45_latest_purchase
    trigger: state
    id: 최근 당첨번호가 변하면
    enabled: true
    attribute: barcode
conditions: []
actions:
  - alias: 당첨 알림
    if:
      - condition: trigger
        id:
          - 최근 당첨번호가 변하면
    then:
      - action: notify.mobile_app_sm_f966n
        metadata: {}
        data:
          message: >-
            레추 로또 당첨 결과는 {{
            states('sensor.dhlotto_xxxxxxxx_lotto45_prev_game_1_result') }}, {{
            states('sensor.dhlotto_xxxxxxxx_lotto45_prev_game_2_result') }}, {{
            states('sensor.dhlotto_xxxxxxxx_lotto45_prev_game_3_result') }}, {{
            states('sensor.dhlotto_xxxxxxxx_lotto45_prev_game_4_result') }}, {{
            states('sensor.dhlotto_xxxxxxxx_lotto45_prev_game_5_result') }}  입니다.
    enabled: true
mode: single

